### ISSUE TITLE
lfg-sublistener not recognizing that lfg-twitchapi is present (NodeCG 0.7.4, Node.js 4.2.4)

### ISSUE THREAD

**Issue by mrflamegoat** [SupportClass/lfg-twitchapi#3]
Not entirely sure if this belongs here, or if this belongs in lfg-sublistener.

> info: [nodecg/lib/server] Starting NodeCG 0.7.4 (Running on Node.js v4.2.4)
> info: [nodecg/lib/server] Login security enabled
> info: [nodecg/lib/server/extensions] Mounted lfg-filter extension
> info: [nodecg/lib/server/extensions] Mounted lfg-hypetrain extension
> info: [nodecg/lib/server/extensions] Mounted lfg-nucleus extension
> warn: [lfg-sublistener] lfg-twitchapi not present, API polling will not be available
> info: [nodecg/lib/server/extensions] Mounted lfg-sublistener extension
> info: [nodecg/lib/server/extensions] Mounted lfg-twitchapi extension

Fresh install of everything, so I'm still skimming through to see what's changed. As you can see, the twitchapi extension is mounting after the sublistener. I'm assuming this is the issue, but I'm not familiar enough with the inner workings of NodeCG.

Any insight on this?

**Comment by Lange** [comment]
I believe I have fixed this in [lfg-sublistener v2.0.1](https://github.com/SupportClass/lfg-sublistener/releases/tag/v2.0.1). Can you try that you and verify?

**Comment by mrflamegoat** [comment]
Fixed up, thanks!

Working through a few other things - might have more later.
